import{a as p,S as L,i as l}from"./assets/vendor-CRwkH7JT.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&a(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();p.defaults.baseURL="https://pixabay.com/api/";function f(e,r){d.classList.remove("is-hidden"),n.classList.add("is-hidden");const s={params:{key:"45515322-6acc0c0fe7102921e2f085c71",q:e,per_page:15,page:r,image_type:"photo",orientation:"horizontal",safesearch:!0}};return p.get("",s)}function h(e){return`
    <li class='gallery-item'>
        <a class='gallery-link' href='${e.largeImageURL}'>
        <img class='gallery-img' src='${e.webformatURL}' alt='${e.tags}'>
        <div class='img-info'>
        </a>
        <p><span>Likes</span> ${e.likes}</p>
        <p><span>Views</span> ${e.views}</p>
        <p><span>Comments</span> ${e.comments}</p>
        <p><span>Downloads</span> ${e.downloads}</p>
        </div>
    </li>`}const g=document.querySelector(".form"),w=document.querySelector(".form-input"),u=document.querySelector(".gallery-list"),d=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");g.addEventListener("submit",S);n.addEventListener("click",b);const y=new L(".gallery-item a",{captionsData:"alt"});let c="",i=1;async function S(e){if(e.preventDefault(),u.innerHTML="",c=w.value,c!==""){i=1;try{const r=await f(c,i);if(r.data.hits.length===0){d.classList.add("is-hidden"),l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"white",messageSize:"16",color:"red",iconColor:"white"});return}const s=r.data.hits.map(a=>h(a)).join("");d.classList.add("is-hidden"),u.innerHTML=s,y.refresh(),n.classList.remove("is-hidden"),r.data.total<=15&&n.classList.add("is-hidden"),g.reset()}catch(r){l.error({message:r,position:"center",messageColor:"white",messageSize:"16",color:"red",iconColor:"white"})}}}async function b(){i++;try{const e=await f(c,i);d.classList.add("is-hidden");const r=e.data.hits.map(t=>h(t)).join("");u.insertAdjacentHTML("beforeend",r),y.refresh();const a=document.querySelector("li").getBoundingClientRect().height;window.scrollBy({top:2*a,behavior:"smooth"}),i===Number.parseInt(e.data.total/15)&&(n.classList.add("is-hidden"),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",messageSize:"16"}))}catch(e){l.error({message:e,position:"center",messageColor:"white",messageSize:"16",color:"red",iconColor:"white"})}}
//# sourceMappingURL=index.js.map
